# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 15e76ee09d3b562ff414acbba6a5009d982f6b34153434f4848c6e62b309992cfc3219eedfdb203283850b47d0db8185da1f8b8f91ebc8ee4ac474cde372aa3c

test:
  secret_key_base: 9a7a54130338339edf044ffbeae4b807a49739bcdc26b85932e198e8ba504ae1c24eb1a1f72c966c0e6a0b6aa07280d482bf17b35c0ba447bc82f520f11df600

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
